build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10
    ignoreAnnotated:
      - 'Composable'
  TooManyFunctions:
    ignoreAnnotatedFunctions:
      - 'Composable'
      - 'Preview'

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Z_0-9]*'

style:
  MagicNumber:
    ignoreAnnotated:
      - 'Composable'
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'
  MaxLineLength:
    maxLineLength: 120